name: Sync to ifixshopify.com Repository

on:
  push:
    branches: ["main"]
    paths:
      - "sites/ifixshopify.com/**"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: gtmsetupservice/ifixshopify.com
          token: ${{ secrets.GH_PAT }}
          path: target-repo

      - name: Sync content
        run: |
          # Remove all existing content in target repo (except .git and .github)
          cd target-repo
          find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name '.github' -exec rm -rf {} +

          # Copy content from source subdirectory
          cp -r ../sites/ifixshopify.com/* .

          # Configure git
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

          # Commit and push changes
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to sync"
          else
            git commit -m "Sync from business-in-a-box (${GITHUB_SHA:0:7})"
            git push origin main
          fi
